CREATE TABLE Users (id INT UNSIGNED AUTO_INCREMENT NOT NULL, username VARCHAR(64) NOT NULL, e_mail VARCHAR(320) NOT NULL UNIQUE, pass CHAR(60) NOT NULL, info VARCHAR(200), profile_picture VARCHAR(100), PRIMARY KEY (id));

CREATE TABLE `Groups` (id INT UNSIGNED AUTO_INCREMENT NOT NULL, group_name VARCHAR(64) NOT NULL, group_description VARCHAR(200), picture VARCHAR(100), owner_id INT UNSIGNED NOT NULL, FOREIGN KEY (owner_id) REFERENCES Users(id), PRIMARY KEY (id));

CREATE TABLE Roles (id INT UNSIGNED AUTO_INCREMENT NOT NULL, group_id INT UNSIGNED NOT NULL, role_name VARCHAR(64) NOT NULL, role_color VARCHAR(7) NOT NULL, permissions INT UNSIGNED NOT NULL, FOREIGN KEY (group_id) REFERENCES `Groups`(id), PRIMARY KEY (id)); 

CREATE TABLE GroupMembership (user_id INT UNSIGNED NOT NULL, group_id INT UNSIGNED NOT NULL, FOREIGN KEY (user_id) REFERENCES Users(id), FOREIGN KEY (group_id) REFERENCES `Groups`(id), PRIMARY KEY (user_id, group_id));

CREATE TABLE RoleMembership (user_id INT UNSIGNED NOT NULL, role_id INT UNSIGNED NOT NULL, FOREIGN KEY (user_id) REFERENCES Users(id), FOREIGN KEY (role_id) REFERENCES Roles(id), PRIMARY KEY (user_id, role_id));

CREATE TABLE Chats (id INT UNSIGNED AUTO_INCREMENT NOT NULL, group_id INT UNSIGNED, user1_id INT UNSIGNED, user2_id INT UNSIGNED, FOREIGN KEY (user1_id) REFERENCES Users(id), FOREIGN KEY (user2_id) REFERENCES Users(id), FOREIGN KEY (group_id) REFERENCES `Groups`(id), PRIMARY KEY (id)); 

CREATE TABLE ChatMessages (id INT UNSIGNED AUTO_INCREMENT NOT NULL, author_id INT UNSIGNED NOT NULL, chat_id INT UNSIGNED NOT NULL, content TEXT NOT NULL, expires DATETIME, sent DATETIME, edited DATETIME, FOREIGN KEY (author_id) REFERENCES Users(id), FOREIGN KEY (chat_id) REFERENCES Chats(id), PRIMARY KEY (id));

CREATE TABLE Sessions(token VARCHAR(32) NOT NULL, user_id INT UNSIGNED NOT NULL, expires DATETIME, FOREIGN KEY (user_id) REFERENCES Users(id), PRIMARY KEY(token));